#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

ynh_systemctl --service="$app-promtail" --action="stop" --log_path="/var/log/$app/promtail.log"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir" --source_id="loki" --full_replace

ynh_setup_source --dest_dir="$install_dir" --source_id="promtail"

mkdir -p "/etc/$app/loki.d" "/etc/$app/promtail.d"

chmod 700 "/etc/$app"
chown -R "$app:www-data" "/etc/$app"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

ynh_config_add --template="loki-default.yaml" --destination="/etc/$app/loki-default.yaml"

ynh_config_add --template="promtail-default.yaml" --destination="/etc/$app/promtail-default.yaml"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

# Create a dedicated systemd config
ynh_config_add_systemd --template="loki.service"
ynh_config_add_systemd --template="promtail.service" --service="$app-promtail"

yunohost service add "$app" --description="Loki daemon" --log="/var/log/$app/loki.log"
yunohost service add "$app-promtail" --description="Promtail daemon" --log="/var/log/$app/promtail.log"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="/var/log/$app/loki.log" --wait_until="Loki started"
ynh_systemctl --service="$app-promtail" --action="start" --log_path="/var/log/$app/promtail.log" --wait_until="server listening on addresses"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
